# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "291c7bfc6b7ae722958f5ecc5070ee47"
name = "SellfernSync"
application_url = "https://order-sync-shopify.onrender.com"
embedded = true

[access_scopes]
scopes = "read_orders"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://order-sync-shopify.onrender.com/auth/callback" ]

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/create"
  topics = [ "orders/create" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]


[build]
automatically_update_urls_on_dev = true
